#!/usr/bin/env bash

# Copyright 2012 Thomas Jost
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy of
# the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software stributed
# under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
# CONDITIONS OF ANY KIND, either express or implied. See the License for the
# specific language governing permissions and limitations under the License.

source .scripts/common.sh
source .scripts/install.sh
source .scripts/main.sh
[[ -e config ]] && source config

sfc_logo

case "$1" in
    "install"|"clean_db"|"build_server"|"build_client"|"server"|"client")
        sfc_$1
        ;;
    *)
        bold "Usage: $0 install|build|clean_db|server|client"
        echo
        echo -e "- ${BOLD}install${NORMAL} will set up everything you need to run your own buddycloud"
        echo -e "  federation: 3 instances of the server and of the web client."
        echo -e "- ${BOLD}clean_db${NORMAL} will empty the database for all the instances."
        echo -e "- ${BOLD}build_server${NORMAL} will rebuild the buddycloud server (CoffeeScript --> JS)."
        echo -e "- ${BOLD}build_client${NORMAL} will rebuild the buddycloud web client (configure script)."
        echo -e "- ${BOLD}server${NORMAL} will start the servers (Prosody + buddycloud)."
        echo -e "- ${BOLD}client${NORMAL} will start the web client and display the URLs you can use to"
        echo -e "  access them."
        ;;
esac
